### ISSUE TITLE
retry logic on send

### ISSUE THREAD

**Issue by mattkiefer** [mattkiefer/foiamail#32]
make a list of unsent agencies and try again

**Comment by mattkiefer** [comment]
code complete but untested ... this should be tested in some kind of end-to-end testing with Patrick at hand-off.

closing.

**Comment by mattkiefer** [comment]
testing suggestion: add a broken email address and verify it retries once

**Comment by phjudge** [comment]
This works as expected.

One slightly odd behavior is that if the list of agencies gets down to 0, you're still prompted once to prep drafts for an empty list of agencies.
